/**
 * Builds src/assets/fonts/fonts.css + the woff2 files it points at.
 *
 * The origin loads two stylesheets:
 *
 *   https://api.fontshare.com/v2/css?f[]=clash-display@400,500,600,700&display=swap
 *   https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900
 *                                        &family=Playfair+Display:ital,wght@1,400&display=swap
 *
 * Google serves one @font-face per unicode subset, and the clone must reproduce
 * every one of them: if the basic-Latin face (U+0000-00FF) is missing or paired
 * with the wrong file, Latin text silently falls back to system-ui and the page
 * no longer matches the origin.
 *
 * So this script parses each declaration's family / style / weight / src /
 * unicode-range straight out of the origin CSS and re-emits it verbatim with a
 * local url(). Nothing is inferred, and subset names come from the origin's own
 * `/* <subset> *​/` comments rather than being guessed from filenames.
 *
 * Usage: node scripts/build-fonts.mjs
 */
import fs from "node:fs";
import path from "node:path";

const OUT = "src/assets/fonts";
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";

const GOOGLE_CSS =
  "https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&family=Playfair+Display:ital,wght@1,400&display=swap";
const FONTSHARE_CSS =
  "https://api.fontshare.com/v2/css?f[]=clash-display@400,500,600,700&display=swap";

fs.mkdirSync(OUT, { recursive: true });

const slug = (s) => s.replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "").toLowerCase();

async function get(url, as = "text") {
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
  return as === "text" ? res.text() : Buffer.from(await res.arrayBuffer());
}

async function download(url, dest) {
  const buf = await get(url, "buffer");
  fs.writeFileSync(dest, buf);
  return buf.length;
}

/* ── parse: comment-delimited @font-face blocks ─────────────────────────────
   Google emits `/* latin *​/ @font-face { ... }`, so anchoring the regex on the
   preceding comment is what keeps each face tied to its real subset name. */
function parseFaces(css) {
  const re = /\/\*\s*([a-z-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g;
  const faces = [];
  let m;
  while ((m = re.exec(css))) {
    const [, subset, body] = m;
    const pick = (re2) => (re2.exec(body) || [])[1];
    const family = pick(/font-family:\s*'([^']+)'/);
    const style = pick(/font-style:\s*([a-z]+)/) || "normal";
    const weight = pick(/font-weight:\s*([\d ]+)/);
    const src = pick(/src:\s*url\(([^)]+)\)/);
    const range = (pick(/unicode-range:\s*([^;]+)/) || "").trim();
    if (family && src) faces.push({ family, style, weight: weight.trim(), src, range, subset });
  }
  return faces;
}

/* Fontshare ships plain `@font-face` blocks with no subset comments. */
function parseFontshare(css) {
  const re = /@font-face\s*\{([^}]*)\}/g;
  const faces = [];
  let m;
  while ((m = re.exec(css))) {
    const body = m[1];
    const pick = (re2) => (re2.exec(body) || [])[1];
    const family = pick(/font-family:\s*'([^']+)'/);
    const style = pick(/font-style:\s*([a-z]+)/) || "normal";
    const weight = pick(/font-weight:\s*(\d+)/);
    const src = pick(/url\('([^']+\.woff2)'\)/);
    if (family && src) {
      faces.push({
        family,
        style,
        weight,
        src: src.startsWith("//") ? "https:" + src : src,
        range: "",
        subset: "latin",
      });
    }
  }
  return faces;
}

const googleFaces = parseFaces(await get(GOOGLE_CSS));
const fontshareFaces = parseFontshare(await get(FONTSHARE_CSS));
const faces = [...googleFaces, ...fontshareFaces];

console.log(`parsed ${googleFaces.length} Google + ${fontshareFaces.length} Fontshare faces`);

let css = `/* ==========================================================================
   Peken Banyumasan — self-hosted webfonts
   Clash Display (Fontshare) · Montserrat + Playfair Display (Google Fonts, OFL)

   Generated by scripts/build-fonts.mjs from the origin's own font requests.
   Every family / style / weight / unicode-range below is copied verbatim from
   the origin stylesheets; only the src url() is rewritten to a local file.
   Subsets must all be present — dropping the U+0000-00FF face makes Latin text
   fall back to system-ui and the page stops matching the origin.
   ========================================================================== */

`;

let ok = 0;
const seen = new Set();
for (const f of faces) {
  const ext = path.extname(new URL(f.src).pathname) || ".woff2";
  const name = `${slug(f.family)}-${f.style}-${slug(f.weight)}-${f.subset}${ext}`;
  const dest = path.join(OUT, name);
  try {
    // Always re-download: the destination name is derived from family+style+
    // weight+subset, so a pre-existing file with the same name may be a stale
    // asset from an earlier (mis-paired) run. Fonts are small; correctness wins.
    const size = await download(f.src, dest);
    ok += 1;
    seen.add(name);
    css += `@font-face {\n  font-family: '${f.family}';\n  font-style: ${f.style};\n  font-weight: ${f.weight};\n  font-display: swap;\n  src: url('./${name}') format('woff2');\n${f.range ? `  unicode-range: ${f.range};\n` : ""}}\n`;
    console.log(`  ${name}  ${(size / 1024).toFixed(1)} KB  ${f.subset}`);
  } catch (e) {
    console.error(`  FAIL ${f.family} ${f.style} ${f.weight} ${f.subset}: ${e.message}`);
  }
}

// Drop woff2 files no longer referenced (the previous, mis-paired set).
for (const file of fs.readdirSync(OUT)) {
  if (file.endsWith(".woff2") && !seen.has(file)) {
    fs.rmSync(path.join(OUT, file));
    console.log(`  removed stale ${file}`);
  }
}

fs.writeFileSync(path.join(OUT, "fonts.css"), css);
console.log(`\n${ok}/${faces.length} faces -> ${OUT}/fonts.css`);
